### ISSUE TITLE
ルーターの作成

### ISSUE THREAD

**Issue by MIZOGUCHIKoki** [MIZOGUCHIKoki/AuthenticationServer#3]

**Comment by MIZOGUCHIKoki** [comment]
# Mac miniのEthernet Interface名
- `eno2s0f0`
- `enxa0cec8e22288`

**Comment by MIZOGUCHIKoki** [comment]
`traceroute`で1ホップと数えられないのは，TTLを減らしてないからですかね．．．？

**Comment by TH340** [comment]
TTLが減らないのはそれであっていると思います！
自動でデクリメントする・しないのところは関数の仕様を見ないとわからないですね...

**Comment by MIZOGUCHIKoki** [comment]
パケットロスが多いのは，やはりPythonだからでしょうか？

**Comment by TH340** [comment]
おそらくそうだと思います...
もう一つの原因としては、ソフト上でパケット操作するため、遅くなり、ロスが増えるのもあると思います
